#!/usr/bin/env python3
"""
show_blocks.py - Write every preset block out as readable text, resolved.

    python system/show_blocks.py            # write preset_previews/blocks.md
    python system/show_blocks.py --print    # also print it to the terminal

This is the fast way to read a whole block and judge whether it points one
direction. It reads content_base.yaml and presets.yaml fresh every run, so it is
never stale: edit a bullet, re-run, the file updates in place and the editor
picks it up. Keep it open next to content_base.yaml.

Every bullet is printed with its id, so a line that reads wrong can be found in
content_base.yaml immediately. Edits always go in content_base.yaml, never here:
this file is generated and overwritten.

For the actual visual layout, use system/make_preset_pdfs.py instead.
"""
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML not found. Install it with: pip install pyyaml")

ROOT = Path(__file__).parent.parent.resolve()
OUT = ROOT / "preset_previews" / "blocks.md"

base = yaml.safe_load((ROOT / "content_base.yaml").read_text(encoding="utf-8"))
presets = (yaml.safe_load((ROOT / "presets.yaml").read_text(encoding="utf-8")) or {}).get("presets") or {}

variants, roles = {}, base["experience"]
for ri, role in enumerate(roles):
    for pi, point in enumerate(role["points"]):
        for v in point["variants"]:
            variants[v["id"]] = (v["text"], ri)
profiles = {p["id"]: p["text"] for p in base["profiles"]}
projects = {p["id"]: p for p in base.get("projects", [])}
skills = base.get("skills") or {}

out = ["# CV blocks", ""]
out.append("Generated from `content_base.yaml` + `presets.yaml`. Regenerate with `python system/show_blocks.py`. Do not edit this file: every change goes in `content_base.yaml` (to change wording) or `presets.yaml` (to change what a block selects).")
out.append("")

for name, block in presets.items():
    bullets = block.get("bullets") or []
    used = {variants[b][1] for b in bullets if b in variants}
    out.append("---")
    out.append("")
    out.append(f"## {block.get('label', name)}")
    out.append("")
    out.append(f"`{name}` · {len(used)} roles · {len(bullets)} bullets · {len(block.get('projects') or [])} projects")
    out.append("")
    if block.get("use_for"):
        out.append(f"**Use for:** {' '.join(block['use_for'].split())}")
        out.append("")

    pid = block.get("profile")
    out.append(f"### Profile · `{pid}`")
    out.append("")
    out.append(profiles.get(pid, "(missing)"))
    out.append("")

    for ri, role in enumerate(roles):
        mine = [b for b in bullets if b in variants and variants[b][1] == ri]
        if not mine:
            continue
        out.append(f"### {role['title']} @ {role['org']}")
        out.append("")
        out.append(f"*{role['start']} to {role['end']}*")
        out.append("")
        for b in mine:
            out.append(f"- {variants[b][0]} `{b}`")
        out.append("")

    dropped = [f"{r['title']} @ {r['org']}" for ri, r in enumerate(roles) if ri not in used]
    out.append("### Roles left out of this block")
    out.append("")
    out.extend([f"- {d}" for d in dropped] or ["- none"])
    out.append("")

    out.append("### Projects")
    out.append("")
    for prid in block.get("projects") or []:
        pj = projects.get(prid)
        out.append(f"- **{pj['name'] if pj else prid}** `{prid}`")
        for pb in (pj or {}).get("bullets", []):
            out.append(f"    - {pb}")
    out.append("")

    out.append("### Skills")
    out.append("")
    for s in block.get("skills") or list(skills):
        out.append(f"- **{s}**: {', '.join(skills.get(s, []))}")
    out.append("")

text = "\n".join(out)
OUT.parent.mkdir(exist_ok=True)
OUT.write_text(text, encoding="utf-8")

if "--print" in sys.argv:
    print(text)

print(f"Wrote {OUT.relative_to(ROOT)}  ({len(presets)} blocks, {len(text.splitlines())} lines)")
