#!/usr/bin/env python3
"""
show_blocks.py - Write each preset block out as a readable CV, one file per block.

    python system/show_blocks.py                        # all blocks
    python system/show_blocks.py real-estate-investment  # just one

Writes preset_previews/cv_<block>.md, one per block. Each file holds ONLY the CV
itself: header, profile, experience, education, projects, skills, in the same
order the PDF renders them. Every bullet carries its content_base.yaml id, so a
line that reads wrong can be found and edited immediately.

The files are read fresh from content_base.yaml and presets.yaml on every run, so
they are never stale: edit a bullet, re-run, reread. They are generated and
overwritten, so never edit them by hand.
"""
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML not found. Install it with: pip install pyyaml")

ROOT = Path(__file__).parent.parent.resolve()
OUT_DIR = ROOT / "preset_previews"

base = yaml.safe_load((ROOT / "content_base.yaml").read_text(encoding="utf-8"))
presets = (yaml.safe_load((ROOT / "presets.yaml").read_text(encoding="utf-8")) or {}).get("presets") or {}

wanted = [a for a in sys.argv[1:] if not a.startswith("--")] or list(presets)
unknown = [w for w in wanted if w not in presets]
if unknown:
    sys.exit(f"Unknown block(s): {', '.join(unknown)}\nKnown: {', '.join(presets)}")

roles = base["experience"]
variants = {}
for ri, role in enumerate(roles):
    for point in role["points"]:
        for v in point["variants"]:
            variants[v["id"]] = (v["text"], ri)
profiles = {p["id"]: p["text"] for p in base["profiles"]}
projects = {p["id"]: p for p in base.get("projects", [])}
skills = base.get("skills") or {}
meta = base.get("meta") or {}

SKILL_LABELS = {
    "data_and_analysis": "Data & Analysis",
    "digital_tools": "Digital Tools",
    "esg_and_sustainability": "ESG & Sustainability",
    "real_estate_and_urban": "Real Estate & Urban",
    "languages": "Languages",
}

OUT_DIR.mkdir(exist_ok=True)

for name in wanted:
    block = presets[name]
    bullets = block.get("bullets") or []
    out = [f"<!-- Generated by system/show_blocks.py from content_base.yaml + presets.yaml."
           f" Block: {name}. Do not edit: edit content_base.yaml or presets.yaml instead. -->",
           ""]

    out.append(f"# {meta.get('name', '')}")
    out.append("")
    out.append(" · ".join(str(x) for x in [meta.get("location"), meta.get("phone"), meta.get("email")] if x))
    out.append("")

    pid = block.get("profile")
    out += ["## Profile", "", f"{profiles.get(pid, '(missing)')} `{pid}`", ""]

    out += ["## Experience", ""]
    for ri, role in enumerate(roles):
        mine = [b for b in bullets if b in variants and variants[b][1] == ri]
        if not mine:
            continue
        out.append(f"### {role['title']} @ {role['org']}")
        out.append("")
        out.append(f"{role.get('location', '')} · {role['start']} - {role['end']}")
        out.append("")
        for b in mine:
            out.append(f"- {variants[b][0]} `{b}`")
        out.append("")

    out += ["## Education", ""]
    for ed in base.get("education", []):
        out.append(f"- **{ed['degree']}**, {ed['school']}, {ed.get('location', '')} · {ed['start']} - {ed['end']}")
    out.append("")

    out += ["## Projects", ""]
    for prid in block.get("projects") or []:
        pj = projects.get(prid)
        if not pj:
            continue
        head = f"### {pj['name']}"
        if pj.get("org"):
            head += f" @ {pj['org']}"
        out += [head, "", f"`{prid}`", ""]
        for pb in pj.get("bullets", []):
            out.append(f"- {pb}")
        out.append("")

    out += ["## Skills", ""]
    for s in block.get("skills") or list(skills):
        out.append(f"- **{SKILL_LABELS.get(s, s)}**: {', '.join(skills.get(s, []))}")
    out.append("")

    path = OUT_DIR / f"cv_{name}.md"
    path.write_text("\n".join(out), encoding="utf-8")
    used = len({variants[b][1] for b in bullets if b in variants})
    print(f"  {path.relative_to(ROOT)}  ({used} roles, {len(bullets)} bullets)")

# The old single combined file, superseded by one file per block.
legacy = OUT_DIR / "blocks.md"
if legacy.exists():
    legacy.unlink()

print(f"\n{len(wanted)} block(s) written to {OUT_DIR.relative_to(ROOT)}/")
